/*
 * 考研数学三 · 关键公式数据库
 * 字段：id（唯一）、cat（分类）、title（简短名称，用于自测选项）、
 *       front（回忆提示）、back（答案，可含 LaTeX）
 * 所有含 LaTeX 的字符串均使用 String.raw 模板，避免反斜杠转义问题。
 */
window.KAOYAN_MS3 = (function () {
  const R = String.raw;

  const CATS = {
    limit: '极限与连续',
    infinitesimal: '等价无穷小',
    derivative: '导数公式',
    drule: '求导法则',
    integral: '积分公式',
    taylor: '泰勒公式',
    mvt: '中值定理',
    trig: '三角公式',
    inequality: '常用不等式',
    series: '无穷级数',
    ode: '微分方程',
    multi: '多元函数',
    doubleint: '二重积分',
    linalg: '线性代数',
    prob: '概率统计'
  };

  const F = (id, cat, title, front, back) => ({ id, cat, title, front, back });

  const DATA = [
    // ============ 极限与连续 ============
    F('lim01', 'limit', '第一重要极限 sinx/x',
      R`求极限：$$\lim_{x\to 0}\frac{\sin x}{x}$$`,
      R`$$\lim_{x\to 0}\frac{\sin x}{x}=1$$`),
    F('lim02', 'limit', '重要极限 tanx/x',
      R`求极限：$$\lim_{x\to 0}\frac{\tan x}{x}$$`,
      R`$$\lim_{x\to 0}\frac{\tan x}{x}=1$$`),
    F('lim03', 'limit', '重要极限 arcsinx/x',
      R`求极限：$$\lim_{x\to 0}\frac{\arcsin x}{x}$$`,
      R`$$\lim_{x\to 0}\frac{\arcsin x}{x}=1$$`),
    F('lim04', 'limit', '重要极限 arctanx/x',
      R`求极限：$$\lim_{x\to 0}\frac{\arctan x}{x}$$`,
      R`$$\lim_{x\to 0}\frac{\arctan x}{x}=1$$`),
    F('lim05', 'limit', '重要极限 (1-cosx)/x^2',
      R`求极限：$$\lim_{x\to 0}\frac{1-\cos x}{x^{2}}$$`,
      R`$$\lim_{x\to 0}\frac{1-\cos x}{x^{2}}=\frac{1}{2}$$`),
    F('lim06', 'limit', '重要极限 ln(1+x)/x',
      R`求极限：$$\lim_{x\to 0}\frac{\ln(1+x)}{x}$$`,
      R`$$\lim_{x\to 0}\frac{\ln(1+x)}{x}=1$$`),
    F('lim07', 'limit', '重要极限 (e^x-1)/x',
      R`求极限：$$\lim_{x\to 0}\frac{e^{x}-1}{x}$$`,
      R`$$\lim_{x\to 0}\frac{e^{x}-1}{x}=1$$`),
    F('lim08', 'limit', '重要极限 ((1+x)^a-1)/x',
      R`求极限：$$\lim_{x\to 0}\frac{(1+x)^{\alpha}-1}{x}$$`,
      R`$$\lim_{x\to 0}\frac{(1+x)^{\alpha}-1}{x}=\alpha$$`),
    F('lim09', 'limit', '第二重要极限 (1+1/x)^x',
      R`求极限：$$\lim_{x\to \infty}\left(1+\frac{1}{x}\right)^{x}$$`,
      R`$$\lim_{x\to \infty}\left(1+\frac{1}{x}\right)^{x}=e$$`),
    F('lim10', 'limit', '第二重要极限 (1+x)^{1/x}',
      R`求极限：$$\lim_{x\to 0}(1+x)^{\frac{1}{x}}$$`,
      R`$$\lim_{x\to 0}(1+x)^{\frac{1}{x}}=e$$`),
    F('lim11', 'limit', '重要极限 (1+a/x)^x',
      R`求极限：$$\lim_{x\to \infty}\left(1+\frac{a}{x}\right)^{x}$$`,
      R`$$\lim_{x\to \infty}\left(1+\frac{a}{x}\right)^{x}=e^{a}$$`),

    // ============ 等价无穷小 ============
    F('inf01', 'infinitesimal', '等价：sinx~x',
      R`$$x\to 0:\quad \sin x \sim\ ?$$`,
      R`$$\sin x \sim x$$`),
    F('inf02', 'infinitesimal', '等价：tanx~x',
      R`$$x\to 0:\quad \tan x \sim\ ?$$`,
      R`$$\tan x \sim x$$`),
    F('inf03', 'infinitesimal', '等价：arcsinx~x',
      R`$$x\to 0:\quad \arcsin x \sim\ ?$$`,
      R`$$\arcsin x \sim x$$`),
    F('inf04', 'infinitesimal', '等价：arctanx~x',
      R`$$x\to 0:\quad \arctan x \sim\ ?$$`,
      R`$$\arctan x \sim x$$`),
    F('inf05', 'infinitesimal', '等价：ln(1+x)~x',
      R`$$x\to 0:\quad \ln(1+x) \sim\ ?$$`,
      R`$$\ln(1+x) \sim x$$`),
    F('inf06', 'infinitesimal', '等价：e^x-1~x',
      R`$$x\to 0:\quad e^{x}-1 \sim\ ?$$`,
      R`$$e^{x}-1 \sim x$$`),
    F('inf07', 'infinitesimal', '等价：a^x-1~xlna',
      R`$$x\to 0:\quad a^{x}-1 \sim\ ?$$`,
      R`$$a^{x}-1 \sim x\ln a$$`),
    F('inf08', 'infinitesimal', '等价：1-cosx~x^2/2',
      R`$$x\to 0:\quad 1-\cos x \sim\ ?$$`,
      R`$$1-\cos x \sim \frac{1}{2}x^{2}$$`),
    F('inf09', 'infinitesimal', '等价：(1+x)^a-1~ax',
      R`$$x\to 0:\quad (1+x)^{\alpha}-1 \sim\ ?$$`,
      R`$$(1+x)^{\alpha}-1 \sim \alpha x$$`),
    F('inf10', 'infinitesimal', '等价：x-sinx~x^3/6',
      R`$$x\to 0:\quad x-\sin x \sim\ ?$$`,
      R`$$x-\sin x \sim \frac{x^{3}}{6}$$`),
    F('inf11', 'infinitesimal', '等价：tanx-x~x^3/3',
      R`$$x\to 0:\quad \tan x - x \sim\ ?$$`,
      R`$$\tan x - x \sim \frac{x^{3}}{3}$$`),
    F('inf12', 'infinitesimal', '等价：x-ln(1+x)~x^2/2',
      R`$$x\to 0:\quad x-\ln(1+x) \sim\ ?$$`,
      R`$$x-\ln(1+x) \sim \frac{x^{2}}{2}$$`),
    F('inf13', 'infinitesimal', '等价：x-arctanx~x^3/3',
      R`$$x\to 0:\quad x-\arctan x \sim\ ?$$`,
      R`$$x-\arctan x \sim \frac{x^{3}}{3}$$`),

    // ============ 导数公式 ============
    F('d01', 'derivative', '(x^n) 求导',
      R`求导数：$$f(x)=x^{n}$$`,
      R`$$f'(x)=n\,x^{n-1}$$`),
    F('d02', 'derivative', '(e^x) 求导',
      R`求导数：$$f(x)=e^{x}$$`,
      R`$$f'(x)=e^{x}$$`),
    F('d03', 'derivative', '(a^x) 求导',
      R`求导数：$$f(x)=a^{x}$$`,
      R`$$f'(x)=a^{x}\ln a$$`),
    F('d04', 'derivative', '(lnx) 求导',
      R`求导数：$$f(x)=\ln x$$`,
      R`$$f'(x)=\frac{1}{x}$$`),
    F('d05', 'derivative', '(log_a x) 求导',
      R`求导数：$$f(x)=\log_{a} x$$`,
      R`$$f'(x)=\frac{1}{x\ln a}$$`),
    F('d06', 'derivative', '(sinx) 求导',
      R`求导数：$$f(x)=\sin x$$`,
      R`$$f'(x)=\cos x$$`),
    F('d07', 'derivative', '(cosx) 求导',
      R`求导数：$$f(x)=\cos x$$`,
      R`$$f'(x)=-\sin x$$`),
    F('d08', 'derivative', '(tanx) 求导',
      R`求导数：$$f(x)=\tan x$$`,
      R`$$f'(x)=\sec^{2} x=\frac{1}{\cos^{2}x}$$`),
    F('d09', 'derivative', '(cotx) 求导',
      R`求导数：$$f(x)=\cot x$$`,
      R`$$f'(x)=-\csc^{2} x=-\frac{1}{\sin^{2}x}$$`),
    F('d10', 'derivative', '(secx) 求导',
      R`求导数：$$f(x)=\sec x$$`,
      R`$$f'(x)=\sec x\tan x$$`),
    F('d11', 'derivative', '(cscx) 求导',
      R`求导数：$$f(x)=\csc x$$`,
      R`$$f'(x)=-\csc x\cot x$$`),
    F('d12', 'derivative', '(arcsinx) 求导',
      R`求导数：$$f(x)=\arcsin x$$`,
      R`$$f'(x)=\frac{1}{\sqrt{1-x^{2}}}$$`),
    F('d13', 'derivative', '(arccosx) 求导',
      R`求导数：$$f(x)=\arccos x$$`,
      R`$$f'(x)=-\frac{1}{\sqrt{1-x^{2}}}$$`),
    F('d14', 'derivative', '(arctanx) 求导',
      R`求导数：$$f(x)=\arctan x$$`,
      R`$$f'(x)=\frac{1}{1+x^{2}}$$`),
    F('d15', 'derivative', '(arccotx) 求导',
      R`求导数：$$f(x)=\operatorname{arccot} x$$`,
      R`$$f'(x)=-\frac{1}{1+x^{2}}$$`),

    // ============ 求导法则 ============
    F('dr01', 'drule', '线性法则',
      R`写出函数和差与数乘的求导法则`,
      R`$$(u\pm v)'=u'\pm v',\qquad (Cu)'=C u'$$`),
    F('dr02', 'drule', '乘法法则',
      R`写出乘积的求导法则`,
      R`$$(uv)'=u'v+uv'$$`),
    F('dr03', 'drule', '除法法则',
      R`写出商的求导法则`,
      R`$$\left(\frac{u}{v}\right)'=\frac{u'v-uv'}{v^{2}}$$`),
    F('dr04', 'drule', '链式法则',
      R`写出复合函数求导的链式法则`,
      R`$$\frac{dy}{dx}=\frac{dy}{du}\cdot\frac{du}{dx}$$`),
    F('dr05', 'drule', '反函数求导',
      R`写出反函数的求导法则`,
      R`$$\left[f^{-1}(y)\right]'=\frac{1}{f'(x)}$$`),
    F('dr06', 'drule', '参数方程求导',
      R`参数方程求导：$$x=x(t),\ y=y(t)$$`,
      R`$$\frac{dy}{dx}=\frac{dy/dt}{dx/dt}$$`),

    // ============ 积分公式 ============
    F('int01', 'integral', '∫k dx',
      R`求不定积分：$$\int k\,dx$$`,
      R`$$\int k\,dx=kx+C$$`),
    F('int02', 'integral', '∫x^n dx',
      R`求不定积分：$$\int x^{n}\,dx$$`,
      R`$$\int x^{n}\,dx=\frac{x^{n+1}}{n+1}+C\quad(n\neq -1)$$`),
    F('int03', 'integral', '∫1/x dx',
      R`求不定积分：$$\int \frac{1}{x}\,dx$$`,
      R`$$\int \frac{1}{x}\,dx=\ln|x|+C$$`),
    F('int04', 'integral', '∫e^x dx',
      R`求不定积分：$$\int e^{x}\,dx$$`,
      R`$$\int e^{x}\,dx=e^{x}+C$$`),
    F('int05', 'integral', '∫a^x dx',
      R`求不定积分：$$\int a^{x}\,dx$$`,
      R`$$\int a^{x}\,dx=\frac{a^{x}}{\ln a}+C$$`),
    F('int06', 'integral', '∫sinx dx',
      R`求不定积分：$$\int \sin x\,dx$$`,
      R`$$\int \sin x\,dx=-\cos x+C$$`),
    F('int07', 'integral', '∫cosx dx',
      R`求不定积分：$$\int \cos x\,dx$$`,
      R`$$\int \cos x\,dx=\sin x+C$$`),
    F('int08', 'integral', '∫tanx dx',
      R`求不定积分：$$\int \tan x\,dx$$`,
      R`$$\int \tan x\,dx=-\ln|\cos x|+C$$`),
    F('int09', 'integral', '∫cotx dx',
      R`求不定积分：$$\int \cot x\,dx$$`,
      R`$$\int \cot x\,dx=\ln|\sin x|+C$$`),
    F('int10', 'integral', '∫secx dx',
      R`求不定积分：$$\int \sec x\,dx$$`,
      R`$$\int \sec x\,dx=\ln|\sec x+\tan x|+C$$`),
    F('int11', 'integral', '∫cscx dx',
      R`求不定积分：$$\int \csc x\,dx$$`,
      R`$$\int \csc x\,dx=\ln|\csc x-\cot x|+C$$`),
    F('int12', 'integral', '∫sec^2x dx',
      R`求不定积分：$$\int \sec^{2}x\,dx$$`,
      R`$$\int \sec^{2}x\,dx=\tan x+C$$`),
    F('int13', 'integral', '∫csc^2x dx',
      R`求不定积分：$$\int \csc^{2}x\,dx$$`,
      R`$$\int \csc^{2}x\,dx=-\cot x+C$$`),
    F('int14', 'integral', '∫secx·tanx dx',
      R`求不定积分：$$\int \sec x\tan x\,dx$$`,
      R`$$\int \sec x\tan x\,dx=\sec x+C$$`),
    F('int15', 'integral', '∫cscx·cotx dx',
      R`求不定积分：$$\int \csc x\cot x\,dx$$`,
      R`$$\int \csc x\cot x\,dx=-\csc x+C$$`),
    F('int16', 'integral', '∫1/(1+x^2) dx',
      R`求不定积分：$$\int \frac{1}{1+x^{2}}\,dx$$`,
      R`$$\int \frac{1}{1+x^{2}}\,dx=\arctan x+C$$`),
    F('int17', 'integral', '∫1/√(1-x^2) dx',
      R`求不定积分：$$\int \frac{1}{\sqrt{1-x^{2}}}\,dx$$`,
      R`$$\int \frac{1}{\sqrt{1-x^{2}}}\,dx=\arcsin x+C$$`),
    F('int18', 'integral', '∫1/(a^2+x^2) dx',
      R`求不定积分：$$\int \frac{1}{a^{2}+x^{2}}\,dx$$`,
      R`$$\int \frac{1}{a^{2}+x^{2}}\,dx=\frac{1}{a}\arctan\frac{x}{a}+C$$`),
    F('int19', 'integral', '∫1/(x^2-a^2) dx',
      R`求不定积分：$$\int \frac{1}{x^{2}-a^{2}}\,dx$$`,
      R`$$\int \frac{1}{x^{2}-a^{2}}\,dx=\frac{1}{2a}\ln\left|\frac{x-a}{x+a}\right|+C$$`),
    F('int20', 'integral', '∫1/(a^2-x^2) dx',
      R`求不定积分：$$\int \frac{1}{a^{2}-x^{2}}\,dx$$`,
      R`$$\int \frac{1}{a^{2}-x^{2}}\,dx=\frac{1}{2a}\ln\left|\frac{a+x}{a-x}\right|+C$$`),
    F('int21', 'integral', '∫1/√(x^2±a^2) dx',
      R`求不定积分：$$\int \frac{1}{\sqrt{x^{2}\pm a^{2}}}\,dx$$`,
      R`$$\int \frac{1}{\sqrt{x^{2}\pm a^{2}}}\,dx=\ln\left|x+\sqrt{x^{2}\pm a^{2}}\right|+C$$`),
    F('int22', 'integral', '∫1/√(a^2-x^2) dx',
      R`求不定积分：$$\int \frac{1}{\sqrt{a^{2}-x^{2}}}\,dx$$`,
      R`$$\int \frac{1}{\sqrt{a^{2}-x^{2}}}\,dx=\arcsin\frac{x}{a}+C$$`),

    // ============ 泰勒公式 ============
    F('tay01', 'taylor', '麦克劳林：e^x',
      R`写出 $e^{x}$ 的麦克劳林展开式`,
      R`$$e^{x}=1+x+\frac{x^{2}}{2!}+\frac{x^{3}}{3!}+\cdots+\frac{x^{n}}{n!}+o(x^{n})$$`),
    F('tay02', 'taylor', '麦克劳林：sinx',
      R`写出 $\sin x$ 的麦克劳林展开式`,
      R`$$\sin x=x-\frac{x^{3}}{3!}+\frac{x^{5}}{5!}-\cdots+(-1)^{n}\frac{x^{2n+1}}{(2n+1)!}+o(x^{2n+1})$$`),
    F('tay03', 'taylor', '麦克劳林：cosx',
      R`写出 $\cos x$ 的麦克劳林展开式`,
      R`$$\cos x=1-\frac{x^{2}}{2!}+\frac{x^{4}}{4!}-\cdots+(-1)^{n}\frac{x^{2n}}{(2n)!}+o(x^{2n})$$`),
    F('tay04', 'taylor', '麦克劳林：ln(1+x)',
      R`写出 $\ln(1+x)$ 的麦克劳林展开式`,
      R`$$\ln(1+x)=x-\frac{x^{2}}{2}+\frac{x^{3}}{3}-\cdots+(-1)^{n-1}\frac{x^{n}}{n}+o(x^{n})$$`),
    F('tay05', 'taylor', '麦克劳林：(1+x)^a',
      R`写出 $(1+x)^{\alpha}$ 的麦克劳林展开式`,
      R`$$(1+x)^{\alpha}=1+\alpha x+\frac{\alpha(\alpha-1)}{2!}x^{2}+\cdots+\frac{\alpha(\alpha-1)\cdots(\alpha-n+1)}{n!}x^{n}+o(x^{n})$$`),
    F('tay06', 'taylor', '麦克劳林：1/(1-x)',
      R`写出 $\dfrac{1}{1-x}$ 的麦克劳林展开式`,
      R`$$\frac{1}{1-x}=1+x+x^{2}+\cdots+x^{n}+o(x^{n})$$`),
    F('tay07', 'taylor', '麦克劳林：1/(1+x)',
      R`写出 $\dfrac{1}{1+x}$ 的麦克劳林展开式`,
      R`$$\frac{1}{1+x}=1-x+x^{2}-x^{3}+\cdots+(-1)^{n}x^{n}+o(x^{n})$$`),
    F('tay08', 'taylor', '麦克劳林：tanx',
      R`写出 $\tan x$ 的麦克劳林展开式（前几项）`,
      R`$$\tan x=x+\frac{x^{3}}{3}+\frac{2x^{5}}{15}+o(x^{5})$$`),
    F('tay09', 'taylor', '麦克劳林：arcsinx',
      R`写出 $\arcsin x$ 的麦克劳林展开式（前几项）`,
      R`$$\arcsin x=x+\frac{x^{3}}{6}+\frac{3x^{5}}{40}+o(x^{5})$$`),
    F('tay10', 'taylor', '麦克劳林：arctanx',
      R`写出 $\arctan x$ 的麦克劳林展开式（前几项）`,
      R`$$\arctan x=x-\frac{x^{3}}{3}+\frac{x^{5}}{5}-\frac{x^{7}}{7}+\cdots$$`),

    // ============ 中值定理 ============
    F('mvt01', 'mvt', '罗尔定理',
      R`叙述罗尔定理的条件与结论`,
      R`若 $f(x)$ 在 $[a,b]$ 上连续，在 $(a,b)$ 内可导，且 $f(a)=f(b)$，则存在 $\xi\in(a,b)$，使 $f'(\xi)=0$。`),
    F('mvt02', 'mvt', '拉格朗日中值定理',
      R`叙述拉格朗日中值定理`,
      R`若 $f(x)$ 在 $[a,b]$ 上连续，在 $(a,b)$ 内可导，则存在 $\xi\in(a,b)$，使$$f(b)-f(a)=f'(\xi)(b-a)$$`),
    F('mvt03', 'mvt', '柯西中值定理',
      R`叙述柯西中值定理`,
      R`若 $f,g$ 在 $[a,b]$ 上连续，在 $(a,b)$ 内可导且 $g'(x)\neq 0$，则存在 $\xi\in(a,b)$，使$$\frac{f(b)-f(a)}{g(b)-g(a)}=\frac{f'(\xi)}{g'(\xi)}$$`),
    F('mvt04', 'mvt', '泰勒中值定理',
      R`写出带拉格朗日余项的泰勒公式`,
      R`$$f(x)=\sum_{k=0}^{n}\frac{f^{(k)}(x_{0})}{k!}(x-x_{0})^{k}+R_{n}(x),$$其中$$R_{n}(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_{0})^{n+1}$$`),

    // ============ 三角公式 ============
    F('trig01', 'trig', '平方关系 sin^2+cos^2',
      R`写出基本平方关系式`,
      R`$$\sin^{2}x+\cos^{2}x=1$$`),
    F('trig02', 'trig', '平方关系 1+tan^2',
      R`写出 $\tan x$ 与 $\sec x$ 的平方关系`,
      R`$$1+\tan^{2}x=\sec^{2}x$$`),
    F('trig03', 'trig', '平方关系 1+cot^2',
      R`写出 $\cot x$ 与 $\csc x$ 的平方关系`,
      R`$$1+\cot^{2}x=\csc^{2}x$$`),
    F('trig04', 'trig', '和角 sin(a+b)',
      R`写出 $\sin(a+b)$ 的展开式`,
      R`$$\sin(a+b)=\sin a\cos b+\cos a\sin b$$`),
    F('trig05', 'trig', '和角 cos(a+b)',
      R`写出 $\cos(a+b)$ 的展开式`,
      R`$$\cos(a+b)=\cos a\cos b-\sin a\sin b$$`),
    F('trig06', 'trig', '二倍角 sin2x',
      R`写出二倍角公式 $\sin 2x$`,
      R`$$\sin 2x=2\sin x\cos x$$`),
    F('trig07', 'trig', '二倍角 cos2x',
      R`写出二倍角公式 $\cos 2x$ 的三种形式`,
      R`$$\cos 2x=\cos^{2}x-\sin^{2}x=2\cos^{2}x-1=1-2\sin^{2}x$$`),
    F('trig08', 'trig', '二倍角 tan2x',
      R`写出二倍角公式 $\tan 2x$`,
      R`$$\tan 2x=\frac{2\tan x}{1-\tan^{2}x}$$`),
    F('trig09', 'trig', '半角 sin^2(x/2)',
      R`写出半角公式 $\sin^{2}\frac{x}{2}$`,
      R`$$\sin^{2}\frac{x}{2}=\frac{1-\cos x}{2}$$`),
    F('trig10', 'trig', '半角 cos^2(x/2)',
      R`写出半角公式 $\cos^{2}\frac{x}{2}$`,
      R`$$\cos^{2}\frac{x}{2}=\frac{1+\cos x}{2}$$`),
    F('trig11', 'trig', '积化和差 sinacosb',
      R`写出积化和差公式 $\sin a\cos b$`,
      R`$$\sin a\cos b=\frac{1}{2}\left[\sin(a+b)+\sin(a-b)\right]$$`),
    F('trig12', 'trig', '和差化积 sina+sinb',
      R`写出和差化积公式 $\sin a+\sin b$`,
      R`$$\sin a+\sin b=2\sin\frac{a+b}{2}\cos\frac{a-b}{2}$$`),
    F('trig13', 'trig', '辅助角公式',
      R`写出辅助角公式 $a\sin x+b\cos x$`,
      R`$$a\sin x+b\cos x=\sqrt{a^{2}+b^{2}}\,\sin(x+\varphi),\quad \tan\varphi=\frac{b}{a}$$`),

    // ============ 常用不等式 ============
    F('ineq01', 'inequality', '|sinx|≤|x|',
      R`写出 $\sin x$ 与 $x$ 的常用不等式`,
      R`$$|\sin x|\le |x|$$`),
    F('ineq02', 'inequality', 'sinx<x<tanx',
      R`在 $(0,\frac{\pi}{2})$ 内，$\sin x、x、\tan x$ 的大小关系`,
      R`$$\sin x<x<\tan x\qquad\left(0<x<\frac{\pi}{2}\right)$$`),
    F('ineq03', 'inequality', 'e^x≥1+x',
      R`写出 $e^{x}$ 的常用不等式`,
      R`$$e^{x}\ge 1+x\qquad(x\in\mathbb{R})$$`),
    F('ineq04', 'inequality', 'ln(1+x)≤x',
      R`写出 $\ln(1+x)$ 的常用不等式`,
      R`$$\ln(1+x)\le x\qquad(x>-1)$$`),
    F('ineq05', 'inequality', '基本不等式 a+b≥2√ab',
      R`写出基本不等式（均值不等式）`,
      R`$$\frac{a+b}{2}\ge\sqrt{ab}\qquad(a,b>0)$$`),
    F('ineq06', 'inequality', '柯西不等式',
      R`写出柯西不等式`,
      R`$$(a^{2}+b^{2})(c^{2}+d^{2})\ge(ac+bd)^{2}$$`),

    // ============ 无穷级数 ============
    F('ser01', 'series', '几何级数收敛条件',
      R`几何级数 $\sum_{n=0}^{\infty}q^{n}$ 的收敛条件与和`,
      R`$$\sum_{n=0}^{\infty}q^{n}\ \text{收敛}\iff |q|<1,\quad \text{和为}\ \frac{1}{1-q}$$`),
    F('ser02', 'series', 'p级数收敛条件',
      R`$p$ 级数 $\sum_{n=1}^{\infty}\frac{1}{n^{p}}$ 的收敛条件`,
      R`$$\sum_{n=1}^{\infty}\frac{1}{n^{p}}\ \text{收敛}\iff p>1$$`),
    F('ser03', 'series', '等比数列求和',
      R`写出等比数列前 $n$ 项和公式`,
      R`$$S_{n}=\frac{a_{1}(1-q^{n})}{1-q}\quad(q\neq 1)$$`),
    F('ser04', 'series', '调和级数发散',
      R`调和级数 $\sum_{n=1}^{\infty}\frac{1}{n}$ 的敛散性`,
      R`$$\sum_{n=1}^{\infty}\frac{1}{n}\ \text{发散}$$`),
    F('ser05', 'series', '交错级数莱布尼茨判别法',
      R`叙述交错级数的莱布尼茨判别法`,
      R`若 $\{u_{n}\}$ 单调递减趋于 $0$，则 $\sum (-1)^{n}u_{n}$ 收敛。`),
    F('ser06', 'series', '比值判别法',
      R`叙述正项级数的比值（达朗贝尔）判别法`,
      R`设 $\lim_{n\to\infty}\dfrac{u_{n+1}}{u_{n}}=\rho$，则 $\rho<1$ 收敛，$\rho>1$ 发散，$\rho=1$ 无法判定。`),
    F('ser07', 'series', '根值判别法',
      R`叙述正项级数的根值（柯西）判别法`,
      R`设 $\lim_{n\to\infty}\sqrt[n]{u_{n}}=\rho$，则 $\rho<1$ 收敛，$\rho>1$ 发散，$\rho=1$ 无法判定。`),
    F('ser08', 'series', '常用和 1/n^2',
      R`级数 $\sum_{n=1}^{\infty}\frac{1}{n^{2}}$ 的和`,
      R`$$\sum_{n=1}^{\infty}\frac{1}{n^{2}}=\frac{\pi^{2}}{6}$$`),
    F('ser09', 'series', '常用和 1/n(n+1)',
      R`级数 $\sum_{n=1}^{\infty}\frac{1}{n(n+1)}$ 的和`,
      R`$$\sum_{n=1}^{\infty}\frac{1}{n(n+1)}=1$$`),

    // ============ 微分方程 ============
    F('ode01', 'ode', '可分离变量方程',
      R`可分离变量方程 $\dfrac{dy}{dx}=f(x)g(y)$ 的解法`,
      R`分离变量：$$\frac{dy}{g(y)}=f(x)\,dx,\quad \text{两边积分}$$`),
    F('ode02', 'ode', '一阶线性通解公式',
      R`一阶线性微分方程 $y'+P(x)y=Q(x)$ 的通解公式`,
      R`$$y=e^{-\int P\,dx}\left[\int Q\,e^{\int P\,dx}\,dx+C\right]$$`),
    F('ode03', 'ode', '二阶常系数齐次（特征方程）',
      R`二阶常系数齐次方程 $y''+py'+qy=0$ 的特征方程与解`,
      R`特征方程 $r^{2}+pr+q=0$：两不等实根→$y=C_{1}e^{r_{1}x}+C_{2}e^{r_{2}x}$；重根 $r$→$y=(C_{1}+C_{2}x)e^{rx}$；共轭复根 $\alpha\pm\beta i$→$y=e^{\alpha x}(C_{1}\cos\beta x+C_{2}\sin\beta x)$。`),
    F('ode04', 'ode', '一阶差分方程通解',
      R`一阶常系数线性差分方程 $y_{x+1}+ay_{x}=0$ 的通解`,
      R`$$y_{x}=C(-a)^{x}$$`),

    // ============ 多元函数 ============
    F('multi01', 'multi', '全微分公式',
      R`写出二元函数 $z=f(x,y)$ 的全微分`,
      R`$$dz=\frac{\partial z}{\partial x}dx+\frac{\partial z}{\partial y}dy$$`),
    F('multi02', 'multi', '隐函数求导公式',
      R`方程 $F(x,y)=0$ 确定的隐函数求导公式`,
      R`$$\frac{dy}{dx}=-\frac{F_{x}}{F_{y}}$$`),
    F('multi03', 'multi', '二元极值判别式',
      R`写出二元函数极值的判别式`,
      R`记 $A=f_{xx},\ B=f_{xy},\ C=f_{yy}$，判别式 $\Delta=AC-B^{2}$。驻点处：$\Delta>0$ 且 $A>0$→极小；$\Delta>0$ 且 $A<0$→极大；$\Delta<0$→非极值；$\Delta=0$→无法判定。`),
    F('multi04', 'multi', '拉格朗日乘数法',
      R`写出条件极值的拉格朗日乘数法`,
      R`求 $f(x,y)$ 在 $\varphi(x,y)=0$ 下的极值：构造 $L=f+\lambda\varphi$，解方程组 $L_{x}=L_{y}=L_{\lambda}=0$。`),
    F('multi05', 'multi', '多元复合函数链式法则',
      R`$z=f(u,v),\ u=u(x,y),\ v=v(x,y)$ 的链式法则`,
      R`$$\frac{\partial z}{\partial x}=\frac{\partial z}{\partial u}\frac{\partial u}{\partial x}+\frac{\partial z}{\partial v}\frac{\partial v}{\partial x}$$`),

    // ============ 线性代数 ============
    F('la01', 'linalg', '行列式乘法定理',
      R`方阵乘积的行列式`,
      R`$$|AB|=|A|\cdot|B|$$`),
    F('la02', 'linalg', '逆矩阵（伴随矩阵法）',
      R`用伴随矩阵求逆的公式`,
      R`$$A^{-1}=\frac{1}{|A|}A^{*}\qquad(|A|\neq 0)$$`),
    F('la03', 'linalg', '克莱姆法则',
      R`叙述克莱姆法则`,
      R`若系数行列式 $D=|A|\neq 0$，则 $Ax=b$ 有唯一解$$x_{i}=\frac{D_{i}}{D}\ (i=1,2,\dots,n)$$`),
    F('la04', 'linalg', '特征方程',
      R`求矩阵 $A$ 的特征值的特征方程`,
      R`$$|\lambda E-A|=0$$`),
    F('la05', 'linalg', '转置运算',
      R`矩阵乘积的转置`,
      R`$$(AB)^{T}=B^{T}A^{T}$$`),
    F('la06', 'linalg', '逆运算',
      R`矩阵乘积的逆`,
      R`$$(AB)^{-1}=B^{-1}A^{-1}$$`),
    F('la07', 'linalg', '秩的不等式',
      R`写出矩阵秩的常用不等式`,
      R`$$r(A)+r(B)-n\ \le\ r(AB)\ \le\ \min\{r(A),\,r(B)\}$$`),
    F('la08', 'linalg', '行列式按行展开',
      R`$n$ 阶行列式按某行展开`,
      R`$$|A|=\sum_{k=1}^{n}a_{ik}A_{ik}\quad(A_{ik}\ \text{为代数余子式})$$`),
    F('la09', 'linalg', '二次型正定判定',
      R`实对称矩阵（二次型）正定的判定`,
      R`$A$ 正定 $\iff$ 所有特征值 $>0$ $\iff$ 各阶顺序主子式 $>0$。`),

    // ============ 概率统计 ============
    F('pb01', 'prob', '加法公式',
      R`写出概率的加法公式`,
      R`$$P(A\cup B)=P(A)+P(B)-P(AB)$$`),
    F('pb02', 'prob', '乘法公式',
      R`写出概率的乘法公式`,
      R`$$P(AB)=P(A)\cdot P(B\,|\,A)$$`),
    F('pb03', 'prob', '全概率公式',
      R`写出全概率公式`,
      R`若 $A_{1},\dots,A_{n}$ 为完备事件组，则$$P(B)=\sum_{i=1}^{n}P(A_{i})P(B\,|\,A_{i})$$`),
    F('pb04', 'prob', '贝叶斯公式',
      R`写出贝叶斯公式`,
      R`$$P(A_{i}\,|\,B)=\frac{P(A_{i})P(B\,|\,A_{i})}{\sum_{j=1}^{n}P(A_{j})P(B\,|\,A_{j})}$$`),
    F('pb05', 'prob', '方差计算式',
      R`写出方差 $D(X)$ 的计算公式`,
      R`$$D(X)=E(X^{2})-[E(X)]^{2}$$`),
    F('pb06', 'prob', '二项分布数字特征',
      R`二项分布 $X\sim B(n,p)$ 的期望与方差`,
      R`$$E(X)=np,\qquad D(X)=np(1-p)$$`),
    F('pb07', 'prob', '泊松分布数字特征',
      R`泊松分布 $X\sim P(\lambda)$ 的期望与方差`,
      R`$$E(X)=\lambda,\qquad D(X)=\lambda$$`),
    F('pb08', 'prob', '均匀分布数字特征',
      R`均匀分布 $X\sim U(a,b)$ 的期望与方差`,
      R`$$E(X)=\frac{a+b}{2},\qquad D(X)=\frac{(b-a)^{2}}{12}$$`),
    F('pb09', 'prob', '指数分布数字特征',
      R`指数分布 $X\sim E(\lambda)$ 的期望与方差`,
      R`$$E(X)=\frac{1}{\lambda},\qquad D(X)=\frac{1}{\lambda^{2}}$$`),
    F('pb10', 'prob', '正态分布数字特征',
      R`正态分布 $X\sim N(\mu,\sigma^{2})$ 的期望与方差`,
      R`$$E(X)=\mu,\qquad D(X)=\sigma^{2}$$`),
    F('pb11', 'prob', '协方差公式',
      R`写出协方差的定义与计算公式`,
      R`$$\mathrm{Cov}(X,Y)=E(XY)-E(X)E(Y)$$`),
    F('pb12', 'prob', '相关系数公式',
      R`写出相关系数 $\rho$ 的公式`,
      R`$$\rho=\frac{\mathrm{Cov}(X,Y)}{\sqrt{D(X)\,D(Y)}}$$`),
    F('pb13', 'prob', '切比雪夫不等式',
      R`写出切比雪夫不等式`,
      R`$$P\{|X-E(X)|\ge\varepsilon\}\le\frac{D(X)}{\varepsilon^{2}}$$`),
    F('pb14', 'prob', '独立同分布中心极限定理',
      R`叙述独立同分布中心极限定理`,
      R`若 $X_{1},\dots,X_{n}$ 独立同分布，$E(X_{i})=\mu,\ D(X_{i})=\sigma^{2}$，则$$\frac{\sum_{i=1}^{n}X_{i}-n\mu}{\sqrt{n}\,\sigma}\ \overset{d}{\longrightarrow}\ N(0,1)$$`),
    F('pb15', 'prob', '辛钦大数定律',
      R`叙述辛钦大数定律`,
      R`若 $X_{1},\dots,X_{n}$ 独立同分布且 $E(X_{i})=\mu$，则$$\frac{1}{n}\sum_{i=1}^{n}X_{i}\ \overset{P}{\longrightarrow}\ \mu$$`),
    F('pb16', 'prob', '矩估计',
      R`叙述矩估计的基本思想`,
      R`令样本矩等于总体矩，建立方程解得参数的估计量。`),
    F('pb17', 'prob', '最大似然估计',
      R`叙述最大似然估计的基本思想`,
      R`选择使似然函数 $L(\theta)=\prod_{i=1}^{n}f(x_{i};\theta)$ 取最大值的 $\hat{\theta}$ 作为估计。`),

    // ============ 补充：极限与连续 ============
    F('lim12', 'limit', '夹逼准则',
      R`叙述夹逼准则（两边夹）`,
      R`若 $g(x)\le f(x)\le h(x)$，且 $\lim g(x)=\lim h(x)=A$，则 $\lim f(x)=A$。`),
    F('lim13', 'limit', '单调有界准则',
      R`叙述数列收敛的单调有界准则`,
      R`单调递增且有上界（或单调递减且有下界）的数列必收敛。`),
    F('lim14', 'limit', '重要极限 n^(1/n)',
      R`求极限：$$\lim_{n\to\infty}\sqrt[n]{n}$$`,
      R`$$\lim_{n\to\infty}\sqrt[n]{n}=1$$`),
    F('lim15', 'limit', '重要极限 a^(1/n)',
      R`求极限：$$\lim_{n\to\infty}\sqrt[n]{a}\quad(a>0)$$`,
      R`$$\lim_{n\to\infty}\sqrt[n]{a}=1$$`),
    F('lim16', 'limit', '连续的定义',
      R`函数 $f(x)$ 在点 $x_{0}$ 处连续的定义`,
      R`$$\lim_{x\to x_{0}}f(x)=f(x_{0})$$（有定义、极限存在、极限值等于函数值，三者同时成立）`),
    F('lim17', 'limit', '间断点分类',
      R`函数的间断点如何分类？`,
      R`第一类（左右极限都存在）：可去型、跳跃型；第二类（左右极限至少一个不存在）：无穷型、振荡型。`),

    // ============ 补充：求导法则 ============
    F('dr07', 'drule', '莱布尼茨高阶导数',
      R`写出乘积 $uv$ 的 $n$ 阶导数（莱布尼茨公式）`,
      R`$$(uv)^{(n)}=\sum_{k=0}^{n}C_{n}^{k}\,u^{(n-k)}v^{(k)}$$`),
    F('dr08', 'drule', '微分定义',
      R`写出微分 $dy$ 与导数 $f'(x)$ 的关系`,
      R`$$dy=f'(x)\,dx$$（可微与可导等价）`),
    F('dr09', 'drule', '可导与连续',
      R`可导与连续的关系`,
      R`可导必连续，但连续不一定可导。`),
    F('dr10', 'drule', '(sinx) 的 n 阶导',
      R`写出 $(\sin x)^{(n)}$ 的公式`,
      R`$$(\sin x)^{(n)}=\sin\left(x+\frac{n\pi}{2}\right)$$`),
    F('dr11', 'drule', '(cosx) 的 n 阶导',
      R`写出 $(\cos x)^{(n)}$ 的公式`,
      R`$$(\cos x)^{(n)}=\cos\left(x+\frac{n\pi}{2}\right)$$`),
    F('dr12', 'drule', '(a^x) 的 n 阶导',
      R`写出 $(a^{x})^{(n)}$ 的公式`,
      R`$$(a^{x})^{(n)}=a^{x}(\ln a)^{n}$$`),

    // ============ 补充：积分公式 ============
    F('int23', 'integral', '牛顿-莱布尼茨公式',
      R`写出牛顿–莱布尼茨公式`,
      R`$$\int_{a}^{b}f(x)\,dx=F(b)-F(a),\quad \text{其中 } F'(x)=f(x)$$`),
    F('int24', 'integral', '分部积分公式',
      R`写出分部积分公式`,
      R`$$\int u\,dv=uv-\int v\,du$$`),
    F('int25', 'integral', '变限积分求导',
      R`写出变上限积分的求导公式`,
      R`$$\frac{d}{dx}\int_{a}^{g(x)}f(t)\,dt=f(g(x))\,g'(x)$$`),
    F('int26', 'integral', '对称区间定积分',
      R`对称区间上奇、偶函数的定积分`,
      R`偶函数：$$\int_{-a}^{a}f(x)\,dx=2\int_{0}^{a}f(x)\,dx$$奇函数：$$\int_{-a}^{a}f(x)\,dx=0$$`),
    F('int27', 'integral', 'p 积分收敛条件',
      R`反常积分 $\int_{1}^{+\infty}\frac{1}{x^{p}}\,dx$ 的收敛条件`,
      R`$$\int_{1}^{+\infty}\frac{1}{x^{p}}\,dx\ \text{收敛}\iff p>1$$`),
    F('int28', 'integral', '定积分求面积',
      R`由 $y=f(x),\,y=g(x),\,x=a,\,x=b$ 围成的平面图形面积`,
      R`$$A=\int_{a}^{b}\left[f(x)-g(x)\right]\,dx$$`),
    F('int29', 'integral', '旋转体体积',
      R`曲线 $y=f(x)\ (a\le x\le b)$ 绕 $x$ 轴旋转所得旋转体体积`,
      R`$$V=\pi\int_{a}^{b}\left[f(x)\right]^{2}\,dx$$`),

    // ============ 补充：二重积分 ============
    F('dbi01', 'doubleint', '二重积分·直角坐标',
      R`二重积分化为累次积分（直角坐标，$D$ 为 X 型区域）`,
      R`$$\iint_{D}f(x,y)\,dxdy=\int_{a}^{b}dx\int_{\varphi_{1}(x)}^{\varphi_{2}(x)}f(x,y)\,dy$$`),
    F('dbi02', 'doubleint', '二重积分·极坐标',
      R`写出二重积分的极坐标变换`,
      R`$$x=r\cos\theta,\quad y=r\sin\theta,\qquad dx\,dy=r\,dr\,d\theta$$$$\iint_{D}f=\iint_{D}f(r\cos\theta,r\sin\theta)\,r\,dr\,d\theta$$`),
    F('dbi03', 'doubleint', '交换积分次序',
      R`交换二次积分次序的关键步骤`,
      R`由积分限画出积分区域 $D$，再按另一积分次序重新写出累次积分。`),

    // ============ 补充：无穷级数 ============
    F('ser10', 'series', '幂级数收敛半径',
      R`幂级数 $\sum a_{n}x^{n}$ 的收敛半径公式`,
      R`$$R=\frac{1}{\lim_{n\to\infty}\left|\frac{a_{n+1}}{a_{n}}\right|}$$（也可用根值法：$$R=\frac{1}{\lim_{n\to\infty}\sqrt[n]{|a_{n}|}}$$）`),
    F('ser11', 'series', '阿贝尔定理',
      R`叙述阿贝尔定理（幂级数收敛性）`,
      R`幂级数在 $|x|<R$ 内绝对收敛，在收敛区间端点处需单独判断（可能条件收敛）。`),
    F('ser12', 'series', '幂级数逐项求导',
      R`幂级数在收敛区间内的逐项求导与逐项积分性质`,
      R`在收敛区间内可逐项求导与逐项积分，且收敛半径不变——这是求幂级数和函数的常用手段。`),
    F('ser13', 'series', '交错级数余项估计',
      R`交错级数 $\sum (-1)^{n}u_{n}$ 的余项估计`,
      R`$$|R_{n}|\le u_{n+1}$$（用部分和 $S_{n}$ 近似和 $S$ 的误差不超过第 $n+1$ 项的绝对值）`),

    // ============ 补充：微分方程 ============
    F('ode05', 'ode', '非齐次方程特解',
      R`二阶常系数非齐次方程 $y''+py'+qy=f(x)$ 特解 $y^{*}$ 的设定规则`,
      R`设 $f(x)=e^{\lambda x}P_{m}(x)$：若 $\lambda$ 不是特征根，取 $y^{*}=e^{\lambda x}Q_{m}(x)$；若 $\lambda$ 是 $k$ 重特征根，取 $y^{*}=x^{k}e^{\lambda x}Q_{m}(x)$，其中 $Q_{m}(x)$ 为待定的 $m$ 次多项式。`),
    F('ode06', 'ode', '伯努利方程',
      R`伯努利方程 $y'+P(x)y=Q(x)y^{n}$ 的解法`,
      R`令 $z=y^{1-n}$，方程化为关于 $z$ 的一阶线性方程再求解。`),
    F('ode07', 'ode', '齐次微分方程',
      R`齐次方程 $\dfrac{dy}{dx}=f\left(\dfrac{y}{x}\right)$ 的解法`,
      R`令 $u=\dfrac{y}{x}$，则 $y=xu$，化为可分离变量方程求解。`),

    // ============ 补充：线性代数 ============
    F('la10', 'linalg', '矩阵可逆条件',
      R`$n$ 阶矩阵 $A$ 可逆的充要条件`,
      R`$$|A|\neq 0\iff A\ \text{可逆}\iff \text{秩为 }n\iff \text{特征值全非零}$$`),
    F('la11', 'linalg', '伴随矩阵性质',
      R`写出伴随矩阵的基本性质`,
      R`$$AA^{*}=A^{*}A=|A|E,\qquad |A^{*}|=|A|^{n-1}$$`),
    F('la12', 'linalg', '特征值性质',
      R`写出特征值与迹、行列式的关系`,
      R`$$\sum_{i=1}^{n}\lambda_{i}=\mathrm{tr}(A),\qquad \prod_{i=1}^{n}\lambda_{i}=|A|$$`),
    F('la13', 'linalg', '可对角化条件',
      R`$n$ 阶矩阵可对角化的条件`,
      R`$n$ 阶方阵 $A$ 可对角化 $\iff$ $A$ 有 $n$ 个线性无关的特征向量 $\iff$ 每个 $k$ 重特征值恰有 $k$ 个线性无关的特征向量。`),
    F('la14', 'linalg', '实对称矩阵',
      R`实对称矩阵的重要结论`,
      R`实对称矩阵必可正交对角化，且不同特征值对应的特征向量相互正交。`),
    F('la15', 'linalg', '施密特正交化',
      R`写出施密特正交化公式`,
      R`$$\beta_{1}=\alpha_{1},\qquad \beta_{k}=\alpha_{k}-\sum_{j=1}^{k-1}\frac{(\alpha_{k},\beta_{j})}{(\beta_{j},\beta_{j})}\,\beta_{j}$$`),
    F('la16', 'linalg', '线性相关定义',
      R`向量组线性相关的定义`,
      R`若存在不全为零的数 $k_{1},\dots,k_{s}$ 使 $k_{1}\alpha_{1}+\cdots+k_{s}\alpha_{s}=0$，则向量组线性相关；否则线性无关。`),
    F('la17', 'linalg', '基础解系',
      R`齐次线性方程组 $Ax=0$ 的基础解系`,
      R`$Ax=0$ 的基础解系由 $n-r(A)$ 个线性无关的解向量构成。`),
    F('la18', 'linalg', '正交矩阵',
      R`正交矩阵的定义`,
      R`$A$ 为正交矩阵 $\iff A^{T}A=E\iff A^{-1}=A^{T}$。`),

    // ============ 补充：概率统计 ============
    F('pb18', 'prob', '期望的线性性质',
      R`写出期望的线性性质`,
      R`$$E(aX+b)=aE(X)+b,\qquad E(X+Y)=E(X)+E(Y)$$`),
    F('pb19', 'prob', '方差的性质',
      R`写出方差的性质`,
      R`$$D(aX+b)=a^{2}D(X)$$$$D(X\pm Y)=D(X)+D(Y)\pm 2\,\mathrm{Cov}(X,Y)$$（独立时 $\mathrm{Cov}=0$）`),
    F('pb20', 'prob', '边缘分布',
      R`二维连续型随机变量的边缘密度`,
      R`$$f_{X}(x)=\int_{-\infty}^{+\infty}f(x,y)\,dy,\qquad f_{Y}(y)=\int_{-\infty}^{+\infty}f(x,y)\,dx$$`),
    F('pb21', 'prob', '随机变量独立',
      R`随机变量 $X,Y$ 相互独立的判定`,
      R`$X,Y$ 独立 $\iff F(x,y)=F_{X}(x)F_{Y}(y)\iff f(x,y)=f_{X}(x)f_{Y}(y)$。`),
    F('pb22', 'prob', '正态标准化',
      R`写出正态分布的标准化`,
      R`若 $X\sim N(\mu,\sigma^{2})$，则$$\frac{X-\mu}{\sigma}\sim N(0,1)$$`),
    F('pb23', 'prob', '几何分布',
      R`几何分布 $X\sim G(p)$ 的分布律与数字特征`,
      R`$$P(X=k)=(1-p)^{k-1}p,\quad E(X)=\frac{1}{p},\quad D(X)=\frac{1-p}{p^{2}}$$`),
    F('pb24', 'prob', '指数分布密度',
      R`写出指数分布 $E(\lambda)$ 的概率密度`,
      R`$$f(x)=\lambda e^{-\lambda x}\quad(x>0)$$`),
    F('pb25', 'prob', '均匀分布密度',
      R`写出均匀分布 $U(a,b)$ 的概率密度`,
      R`$$f(x)=\frac{1}{b-a},\quad x\in(a,b)$$`),
  ];

  // 元数据：[重要程度 1~5 星, 常考题型]
  const META = {
    // 极限与连续
    lim01: [5, '求极限：0/0 型，直接用重要极限'],
    lim02: [4, '求极限：三角函数比值'],
    lim03: [3, '求极限：反三角比值'],
    lim04: [3, '求极限：反三角比值'],
    lim05: [4, '求极限：1-cosx 型'],
    lim06: [4, '求极限：对数型'],
    lim07: [4, '求极限：指数型'],
    lim08: [4, '求极限：幂指型'],
    lim09: [5, '求极限：1^∞ 型'],
    lim10: [5, '求极限：1^∞ 型'],
    lim11: [4, '求极限：1^∞ 型推广'],
    lim12: [4, '数列极限证明 / 求和型极限'],
    lim13: [4, '数列极限存在性证明'],
    lim14: [3, '求数列极限'],
    lim15: [2, '求数列极限'],
    lim16: [3, '分段函数连续性讨论'],
    lim17: [4, '分段函数间断点判断'],
    // 等价无穷小
    inf01: [5, '极限计算：等价无穷小替换'],
    inf02: [4, '极限计算：等价无穷小替换'],
    inf03: [4, '极限计算：等价无穷小替换'],
    inf04: [4, '极限计算：等价无穷小替换'],
    inf05: [5, '极限计算：等价无穷小替换'],
    inf06: [5, '极限计算：等价无穷小替换'],
    inf07: [3, '极限计算：等价无穷小替换'],
    inf08: [5, '极限计算：等价无穷小替换'],
    inf09: [5, '极限计算：等价无穷小替换'],
    inf10: [4, '极限计算：加减法中的高阶无穷小'],
    inf11: [3, '极限计算：加减法中的高阶无穷小'],
    inf12: [3, '极限计算：加减法中的高阶无穷小'],
    inf13: [3, '极限计算：加减法中的高阶无穷小'],
    // 导数公式
    d01: [5, '求导 / 求微分'],
    d02: [5, '求导 / 求微分'],
    d03: [3, '求导 / 求微分'],
    d04: [5, '求导 / 求微分'],
    d05: [3, '求导 / 求微分'],
    d06: [5, '求导 / 求微分'],
    d07: [5, '求导 / 求微分'],
    d08: [4, '求导 / 求微分'],
    d09: [3, '求导 / 求微分'],
    d10: [2, '求导 / 求微分'],
    d11: [2, '求导 / 求微分'],
    d12: [4, '求导 / 求微分'],
    d13: [3, '求导 / 求微分'],
    d14: [5, '求导 / 求微分'],
    d15: [2, '求导 / 求微分'],
    // 求导法则
    dr01: [5, '求导：和差与数乘'],
    dr02: [5, '求导：乘积'],
    dr03: [5, '求导：商'],
    dr04: [5, '求导：复合函数'],
    dr05: [3, '求导：反函数'],
    dr06: [3, '求导：参数方程'],
    dr07: [3, '高阶导数计算'],
    dr08: [3, '微分定义 / 近似计算'],
    dr09: [3, '可导性与连续性判断'],
    dr10: [3, '高阶导数计算'],
    dr11: [3, '高阶导数计算'],
    dr12: [2, '高阶导数计算'],
    // 积分公式
    int01: [4, '不定积分计算'],
    int02: [5, '不定积分计算'],
    int03: [5, '不定积分计算'],
    int04: [5, '不定积分计算'],
    int05: [3, '不定积分计算'],
    int06: [5, '不定积分计算'],
    int07: [5, '不定积分计算'],
    int08: [4, '不定积分计算'],
    int09: [3, '不定积分计算'],
    int10: [3, '不定积分计算'],
    int11: [3, '不定积分计算'],
    int12: [4, '不定积分计算'],
    int13: [3, '不定积分计算'],
    int14: [3, '不定积分计算'],
    int15: [2, '不定积分计算'],
    int16: [5, '不定积分 / 定积分计算'],
    int17: [4, '不定积分 / 定积分计算'],
    int18: [4, '不定积分 / 定积分计算'],
    int19: [4, '不定积分 / 定积分计算'],
    int20: [3, '不定积分 / 定积分计算'],
    int21: [4, '不定积分 / 定积分计算'],
    int22: [4, '不定积分 / 定积分计算'],
    int23: [5, '定积分计算'],
    int24: [5, '积分计算：乘积型 / 反三角'],
    int25: [5, '变限积分求导 / 极限综合'],
    int26: [4, '对称区间定积分化简'],
    int27: [4, '反常积分敛散性判断'],
    int28: [4, '定积分应用：平面面积'],
    int29: [4, '定积分应用：旋转体体积'],
    // 泰勒公式
    tay01: [5, '泰勒展开 / 求极限 / 高阶导'],
    tay02: [5, '泰勒展开 / 求极限 / 高阶导'],
    tay03: [5, '泰勒展开 / 求极限 / 高阶导'],
    tay04: [5, '泰勒展开 / 求极限 / 高阶导'],
    tay05: [4, '泰勒展开 / 求极限'],
    tay06: [4, '泰勒展开 / 级数求和'],
    tay07: [3, '泰勒展开 / 级数求和'],
    tay08: [3, '泰勒展开（低阶）'],
    tay09: [3, '泰勒展开（低阶）'],
    tay10: [4, '泰勒展开 / 级数求和'],
    // 中值定理
    mvt01: [4, '证明题：存在 ξ 使 f\'(ξ)=0'],
    mvt02: [5, '证明题：中值等式 / 不等式'],
    mvt03: [3, '证明题：两个函数的中值关系'],
    mvt04: [4, '证明题 / 高阶泰勒估计'],
    // 三角公式
    trig01: [5, '三角化简 / 积分计算'],
    trig02: [4, '三角化简 / 积分计算'],
    trig03: [3, '三角化简 / 积分计算'],
    trig04: [4, '三角化简 / 求导积分'],
    trig05: [4, '三角化简 / 求导积分'],
    trig06: [5, '三角化简 / 积分降幂'],
    trig07: [5, '三角化简 / 积分降幂'],
    trig08: [3, '三角化简'],
    trig09: [4, '积分：半角降幂'],
    trig10: [4, '积分：半角降幂'],
    trig11: [3, '三角积分'],
    trig12: [3, '三角化简'],
    trig13: [3, '三角型函数最值 / 化简'],
    // 常用不等式
    ineq01: [3, '证明不等式 / 放缩'],
    ineq02: [3, '证明不等式 / 比较大小'],
    ineq03: [4, '证明不等式 / 放缩'],
    ineq04: [4, '证明不等式 / 放缩'],
    ineq05: [4, '证明不等式 / 最值'],
    ineq06: [4, '证明不等式 / 最值'],
    // 无穷级数
    ser01: [5, '级数求和 / 敛散性判断'],
    ser02: [5, '正项级数敛散性判断'],
    ser03: [4, '数列求和'],
    ser04: [4, '级数敛散性判断'],
    ser05: [4, '交错级数敛散性判断'],
    ser06: [5, '正项级数敛散性判断'],
    ser07: [3, '正项级数敛散性判断'],
    ser08: [3, '数项级数求和'],
    ser09: [3, '数项级数求和（裂项）'],
    ser10: [5, '幂级数收敛域'],
    ser11: [3, '幂级数收敛性讨论'],
    ser12: [4, '幂级数求和函数'],
    ser13: [2, '交错级数近似计算'],
    // 微分方程
    ode01: [5, '解微分方程'],
    ode02: [5, '解一阶线性微分方程'],
    ode03: [5, '解二阶常系数齐次方程'],
    ode04: [4, '数三：解差分方程'],
    ode05: [5, '解二阶常系数非齐次方程'],
    ode06: [3, '解伯努利方程'],
    ode07: [3, '解齐次方程'],
    // 多元函数
    multi01: [5, '求全微分 / 偏导数'],
    multi02: [5, '隐函数求导'],
    multi03: [5, '二元函数极值判定'],
    multi04: [4, '条件极值'],
    multi05: [4, '多元复合函数求偏导'],
    // 二重积分
    dbi01: [5, '二重积分计算（直角坐标）'],
    dbi02: [5, '二重积分计算（极坐标）'],
    dbi03: [5, '二重积分：交换积分次序'],
    // 线性代数
    la01: [5, '行列式计算'],
    la02: [5, '求逆矩阵'],
    la03: [3, '解线性方程组'],
    la04: [5, '求特征值与特征向量'],
    la05: [4, '矩阵运算'],
    la06: [4, '矩阵运算'],
    la07: [3, '矩阵秩的讨论'],
    la08: [5, '行列式按行展开计算'],
    la09: [4, '二次型正定判定'],
    la10: [5, '矩阵可逆性判定'],
    la11: [3, '伴随矩阵计算'],
    la12: [4, '特征值性质（迹/行列式）'],
    la13: [4, '矩阵对角化'],
    la14: [4, '实对称矩阵正交对角化'],
    la15: [3, '向量组正交化'],
    la16: [4, '向量组线性相关性'],
    la17: [4, '齐次方程组基础解系'],
    la18: [3, '正交矩阵判定'],
    // 概率统计
    pb01: [5, '概率计算'],
    pb02: [5, '概率计算（条件概率）'],
    pb03: [5, '概率计算（全概率）'],
    pb04: [5, '概率计算（贝叶斯）'],
    pb05: [5, '数字特征计算'],
    pb06: [5, '二项分布概率与数字特征'],
    pb07: [4, '泊松分布概率与数字特征'],
    pb08: [4, '均匀分布概率与数字特征'],
    pb09: [4, '指数分布概率与数字特征'],
    pb10: [5, '正态分布概率与数字特征'],
    pb11: [4, '协方差计算'],
    pb12: [4, '相关系数计算'],
    pb13: [3, '概率不等式估计'],
    pb14: [4, '中心极限定理近似计算'],
    pb15: [3, '大数定律'],
    pb16: [4, '参数估计：矩估计'],
    pb17: [5, '参数估计：极大似然估计'],
    pb18: [5, '数字特征计算'],
    pb19: [5, '数字特征计算'],
    pb20: [4, '二维随机变量边缘分布'],
    pb21: [4, '随机变量独立性判定'],
    pb22: [5, '正态分布标准化计算'],
    pb23: [2, '几何分布概率与数字特征'],
    pb24: [4, '指数分布密度计算'],
    pb25: [3, '均匀分布密度计算'],
  };

  return { CATS, DATA, META };
})();
